---
- include_vars: ../defaults/main.yml

- name: update system
  apt: upgrade=dist update_cache=yes

- name: Install all base packages
  apt: name="{{ item }}" state=present
  with_items: "{{base_packages}}"

- name: remove apache web server
  apt: name="{{ item }}" state=absent
  with_items:
     - apache2

- name: Install s4cmd
  pip: name=s4cmd state=present
