user_name: jenkins
user_password: jenkins
docker_hub_url_mumbai: { "insecure-registries" : ["docker-hub-m.treebo.com:5000"] }
docker_hub_url_singapore: { "insecure-registries" : ["docker-hub.treebo.com:5000"] }
sudo_file: /etc/sudoers
docker_compose_version: 1.21.0
