filebeat.prospectors:
- type: log
  paths:
    - /var/log/nginx/access.log

  document_type: doc
  tags: ["{{ index_name }}"]
  scan_frequency: 5s
  close_inactive: 2h
  harvester_limit: 100

filebeat.registry_file: /var/lib/filebeat/registry

logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: {{ index_name }}.log
  keepfiles: 7

output.logstash:
  hosts: [ "{{ logstash_host }}" ]